modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[dependencies.deepnether]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.deepnether]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    description='''${mod_description}'''

    [[mods.author]]
        name="${mod_authors}"
